const LIST_MENU = [
  {
    id: "m1",
    categories: "PIZZA",
    name: "Cheese Lover Pizza",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit",
    price: 120000,
    URL: "/images/pizza/cheese-lover-pizza.jpg",
    bestSeller: true,
    recomended: true,
  },
  {
    id: "m2",
    categories: "PIZZA",
    name: "Corn Pizza",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit",
    price: 110000,
    URL: "/images/pizza/corn-pizza.jpg",
    bestSeller: false,
    recomended: true,
  },
  {
    id: "m3",
    categories: "PIZZA",
    name: "Funky Pizza",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit",
    price: 115000,
    URL: "/images/pizza/funky-pizza.jpg",
    bestSeller: false,
    recomended: false,
  },
  {
    id: "m4",
    categories: "PIZZA",
    name: "Green Cream Pizza",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit",
    price: 120000,
    URL: "/images/pizza/green-cream-pizza.jpg",
    bestSeller: false,
    recomended: false,
  },
  {
    id: "m5",
    categories: "PIZZA",
    name: "Greens Pizza",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit",
    price: 111000,
    URL: "/images/pizza/greens-pizza.jpg",
    bestSeller: false,
    recomended: false,
  },
  {
    id: "m6",
    categories: "PIZZA",
    name: "Mashroom Pizza",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit",
    price: 150000,
    URL: "/images/pizza/mashroom-pizza.jpg",
    bestSeller: false,
    recomended: false,
  },
  {
    id: "m7",
    categories: "PIZZA",
    name: "Meat Lover Pizza",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit",
    price: 180000,
    URL: "/images/pizza/meat-lover-pizza.jpg",
    bestSeller: true,
    recomended: true,
  },
  {
    id: "m8",
    categories: "PIZZA",
    name: "Pepper Pizza",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit",
    price: 155000,
    URL: "/images/pizza/pepper-pizza.jpg",
    bestSeller: false,
    recomended: false,
  },
  {
    id: "m9",
    categories: "PIZZA",
    name: "Pepperoni Pizza",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit",
    price: 159900,
    URL: "/images/pizza/pepperoni-pizza.jpg",
    bestSeller: true,
    recomended: true,
  },
  {
    id: "m10",
    categories: "PIZZA",
    name: "Tomato Pizza",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit",
    price: 160000,
    URL: "/images/pizza/pizza-n-tomato.jpg",
    bestSeller: false,
    recomended: false,
  },
  {
    id: "m11",
    categories: "PIZZA",
    name: "Veeg Cheese Pizza",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit",
    price: 160000,
    URL: "/images/pizza/veeg-cheese-pizza.jpg",
    bestSeller: false,
    recomended: false,
  },
  {
    id: "m12",
    categories: "PIZZA",
    name: "Viggies Pizza",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit",
    price: 165000,
    URL: "/images/pizza/viggies-pizza.jpg",
    bestSeller: false,
    recomended: false,
  },
  {
    id: "m13",
    categories: "DRINKS",
    name: "Blue Ocean",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit",
    price: 10000,
    URL: "/images/drinks/blue-ocean.jpg",
    bestSeller: false,
    recomended: true,
  },
  {
    id: "m14",
    categories: "DRINKS",
    name: "Chocolate Milkshake",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit",
    price: 15000,
    URL: "/images/drinks/chocolate-milkshake.jpg",
    bestSeller: false,
    recomended: false,
  },
  {
    id: "m15",
    categories: "DRINKS",
    name: "Cucumber Squash",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit",
    price: 18000,
    URL: "/images/drinks/cucumber-squash.jpg",
    bestSeller: false,
    recomended: false,
  },
  {
    id: "m16",
    categories: "DRINKS",
    name: "Ice Choco",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit",
    price: 18000,
    URL: "/images/drinks/ice-choco.jpg",
    bestSeller: false,
    recomended: false,
  },
  {
    id: "m17",
    categories: "DRINKS",
    name: "Ice Lemon Tea",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit",
    price: 11000,
    URL: "/images/drinks/ice-lemon-tea.jpg",
    bestSeller: false,
    recomended: false,
  },
  {
    id: "m18",
    categories: "DRINKS",
    name: "Ice Tea",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit",
    price: 8000,
    URL: "/images/drinks/ice-tea.jpg",
    bestSeller: false,
    recomended: false,
  },
  {
    id: "m19",
    categories: "RAMEN",
    name: "Classic Ramen",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit",
    price: 35000,
    URL: "/images/ramen/classic-ramen.jpg",
    bestSeller: true,
    recomended: true,
  },
  {
    id: "m20",
    categories: "RAMEN",
    name: "Crab Stick Ramen",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit",
    price: 38000,
    URL: "/images/ramen/crab-stick-ramen.jpg",
    bestSeller: false,
    recomended: true,
  },
  {
    id: "m21",
    categories: "RAMEN",
    name: "Curry Ramen",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit",
    price: 36500,
    URL: "/images/ramen/curry-ramen.jpg",
    bestSeller: false,
    recomended: true,
  },
  {
    id: "m22",
    categories: "RAMEN",
    name: "Duck Meat Ramen",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit",
    price: 37000,
    URL: "/images/ramen/duck-meat-ramen.jpg",
    bestSeller: false,
    recomended: true,
  },
  {
    id: "m23",
    categories: "RAMEN",
    name: "Ebi Ramen",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit",
    price: 40000,
    URL: "/images/ramen/ebi-ramen.jpg",
    bestSeller: true,
    recomended: true,
  },
  {
    id: "m24",
    categories: "RAMEN",
    name: "Green Ramen",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit",
    price: 30000,
    URL: "/images/ramen/green-ramen.jpg",
    bestSeller: false,
    recomended: false,
  },
  {
    id: "m25",
    categories: "RICE",
    name: "Chicken Katsu",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit",
    price: 35000,
    URL: "/images/rice/chicken-katsu.jpg",
    bestSeller: false,
    recomended: true,
  },
  {
    id: "m26",
    categories: "RICE",
    name: "Greens Bowl",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit",
    price: 28000,
    URL: "/images/rice/greens-bowl.jpg",
    bestSeller: false,
    recomended: false,
  },
  {
    id: "m27",
    categories: "RICE",
    name: "Healthy Rice Bowl",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit",
    price: 28000,
    URL: "/images/rice/healty-rice-bowl.jpg",
    bestSeller: false,
    recomended: false,
  },
  {
    id: "m28",
    categories: "RICE",
    name: "Katsu Nasi Kuning",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit",
    price: 25000,
    URL: "/images/rice/katsu-nasi-kuning.jpg",
    bestSeller: false,
    recomended: false,
  },
  {
    id: "m29",
    categories: "RICE",
    name: "Lemon Nasi Goreng",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit",
    price: 30000,
    URL: "/images/rice/lemon-nasi-goreng.jpg",
    bestSeller: true,
    recomended: true,
  },
  {
    id: "m30",
    categories: "RICE",
    name: "Meat Potato Rice",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit",
    price: 33000,
    URL: "/images/rice/meat-potato-rice.jpg",
    bestSeller: false,
    recomended: false,
  },
];

export default LIST_MENU;
